# ============================================
# Mario Party Toolkit
# Author: Nayla Hanegan (naylahanegan@gmail.com)
# Date: 5/12/2024
# License: MIT
# ============================================

# Import necessary functions and modules
from functions import *
from events.marioParty4_coins import *
from events.marioParty4_handicap import *
from events.marioParty4_lotteryPrize import *
from events.marioParty4_mgreplace import *
from events.marioParty4_items import *
from events.marioParty4_battle import *
from events.marioParty4_initialItems import *
from events.marioParty4_spaceReplace import *

# Import custom tkinter module as ctk
import customtkinter as ctk

# Function to create the main interface for Mario Party 1
def create_mario_party_4_interface(frame):
    # Create a tabbed interface
    tabview = ctk.CTkTabview(frame, width=1110, height=885, fg_color=("#fcfcfc", "#323232"))
    tabview.grid(padx=10, pady=10)
    tabview.add("Coins Mods")
    tabview.add("Minigame Replacement")
    tabview.add("Item Mods")
    tabview.add("Initial Items")
    tabview.add("Space Replacement")
    tabview.add("Lottery Rewards")
    tabview.add("Battle Minigame")
    tabview.add("Star Handicaps")
    tabview.set("Coins Mods")

    # Function to create an entry field and checkbox
    def create_entry(tab, row, icon_path, label_text, color, placerholder):
        create_image_icon(tab, icon_path, row, 1)
        label = ctk.CTkLabel(master=tab, text=label_text, font=("Arial", 16))
        label.grid(row=row, column=2, sticky="w", pady=15)
        entry = ctk.CTkEntry(master=tab, width=48, font=("Arial", 16, "bold"), placeholder_text=placerholder)
        entry.grid(row=row, column=3)
        label1 = ctk.CTkLabel(master=tab, text=color, font=("Arial", 16))
        label1.grid(row=row, column=4, sticky="w")
        return entry

    # Create entry fields and checkboxes for Coins Mods tab
    blue_entry = create_entry(tabview.tab("Coins Mods"), 1, "assets/eventTags/blueSpace.png", " Gain  ", " Coins on a Blue Space.", "3")
    red_entry = create_entry(tabview.tab("Coins Mods"), 2, "assets/eventTags/redSpace.png", " Lose  ", " Coins on a Red Space.", "3")
    mgWin_entry = create_entry(tabview.tab("Coins Mods"), 3, "assets/eventTags/miniGame.png", " Gain  ", " Coins when winning a Minigame.", "10")
    star_entry = create_entry(tabview.tab("Coins Mods"), 4, "assets/eventTags/starSpace.png", " Costs ", " Coins to buy a Star.", "20")
    mega_entry = create_entry(tabview.tab("Coins Mods"), 5, "assets/items/megaMushroom.png", " Gain ", " Coins when squishing a player.", "10")
    bowser_entry = create_entry(tabview.tab("Coins Mods"), 6, "assets/items/bowserSuit4.png", " Gain ", " Coins when squishing a player.", "30")
    booHouseStar_entry = create_entry(tabview.tab("Coins Mods"), 7, "assets/eventTags/booHouseStars.png", " Costs ", " Coins when stealing a Star.", "50")
    booHouseCoins_entry = create_entry(tabview.tab("Coins Mods"), 8, "assets/eventTags/booHouseCoins.png", " Costs ", " Coins when stealing coins.", "5")
    booHouseCoinsMin_entry = create_entry(tabview.tab("Coins Mods"), 9, "assets/eventTags/booHouseCoins.png", " Steal ", " Minimum when stealing coins.", "")
    lottery_entry = create_entry(tabview.tab("Coins Mods"), 10, "assets/eventTags/lottery4.png", " Costs ", " Coins to play the Lottery.", "5")
    initial_entry = create_entry(tabview.tab("Coins Mods"), 11, "assets/eventTags/initialCoins.png", " Gain ", " Coins at the start of the game.", "10")

    # Create button to generate coins modification codes
    parse_coins_button = ctk.CTkButton(master=tabview.tab("Coins Mods"), command=lambda: coinsEvent_mp4(blue_entry, red_entry, mgWin_entry, star_entry, mega_entry, booHouseStar_entry, booHouseCoins_entry, lottery_entry, booHouseCoinsMin_entry, bowser_entry, initial_entry), text="Generate Codes")
    parse_coins_button.place(x=10, y=800)

    # List of minigame names
    minigames_list = ["Manta Rings", "Slime Time", "Booksquirm", "Trace Race", "Mario Medley", "Avalanche!", "Domination", "Paratrooper Plunge", "Toad's Quick Draw", "Three Throw", "Photo Finish", "Mr. Blizzard's Brigade", "Bob-omb Breakers", "Long Claw of the Law", "Stamp Out!", "Candlelight Fright", "Makin' Waves", "Hide and Go BOOM!", "Tree Stomp", "Fish n' Drips", "Hop or Pop", "Money Belts", "GOOOOOOAL!!", "Blame it on the Crane", "The Great Deflate", "Revers-a-Bomb", "Right Oar Left?", "Cliffhangers", "Team Treasure Trek", "Pair-a-sailing", "Order Up", "Dungeon Duos", "Beach Volley Folley", "Cheep Cheep Sweep", "Darts of Doom", "Fruits of Doom", "Balloon of Doom", "Chain Chomp Fever", "Paths of Peril", "Bowser's Bigger Blast", "Butterfly Blitz", "Barrel Baron", "Mario Speedwagons", "Bowser Bop", "Mystic Match 'Em", "Archaeologuess", "Goomba's Chip Flip", "Kareening Koopas", "The Final Battle!", "Rumble Fishing", "Take a Breather", "Bowser Wrestling", "Panels of Doom"]   
    # Create labels, comboboxes, and button for Minigame Replacement tab
    replace_label = ctk.CTkLabel(master=tabview.tab("Minigame Replacement"), text=" Replace  ", font=("Arial", 16))
    replace_label.grid(row=0, column=0)
    combobox_mingames_1 = ctk.CTkComboBox(master=tabview.tab("Minigame Replacement"), values=minigames_list)
    combobox_mingames_1.grid(row=0, column=1)
    with_label = ctk.CTkLabel(master=tabview.tab("Minigame Replacement"), text=" with ", font=("Arial", 16))
    with_label.grid(row=0, column=2)
    combobox_mingames_2 = ctk.CTkComboBox(master=tabview.tab("Minigame Replacement"), values=minigames_list)
    combobox_mingames_2.grid(row=0, column=3)
    parse_minigame_button = ctk.CTkButton(master=tabview.tab("Minigame Replacement"), command=lambda: mgReplaceEvent_mp4(combobox_mingames_1, combobox_mingames_2, minigames_list), text="Generate Codes")
    parse_minigame_button.place(x=10, y=800)

    # ITEM GEN
    scrollable_frame = ctk.CTkFrame(master=tabview.tab("Item Mods"), fg_color=("#fcfcfc", "#2e2e2e"))
    scrollable_frame.grid(row=0, column=0, sticky="nsew", pady=(0, 50))
    # Configure grid to allow stretching
    tabview.tab("Item Mods").grid_rowconfigure(0, weight=1)
    tabview.tab("Item Mods").grid_columnconfigure(0, weight=1)
    scrollable_frame.grid_rowconfigure(0, weight=1)

    # Create a canvas for scrolling
    canvas = ctk.CTkCanvas(master=scrollable_frame, bg="#2e2e2e", highlightthickness=0)
    canvas.grid(row=0, column=0, sticky="nsew")

    # Create a vertical scrollbar linked to the canvas
    scrollbar = ctk.CTkScrollbar(master=scrollable_frame, orientation="vertical", command=canvas.yview, fg_color=("#ffffff", "#3a3a3a"))
    scrollbar.grid(row=0, column=1, sticky="ns")

    # Configure the canvas to work with the scrollbar
    canvas.configure(yscrollcommand=scrollbar.set)

    # Create a frame inside the canvas to hold the content
    content_frame = ctk.CTkFrame(master=canvas, fg_color=("#fcfcfc", "#2e2e2e"))
    canvas.create_window((0, 0), window=content_frame, anchor="nw")

    # Function to update the scroll region
    def update_scroll_region(event):
        canvas.configure(scrollregion=canvas.bbox("all"))

    content_frame.bind("<Configure>", update_scroll_region)
    
    # Configure the canvas to fill the width of the scrollable frame
    scrollable_frame.grid_columnconfigure(0, weight=1)  # Ensure the canvas fills the width
    canvas.grid_rowconfigure(0, weight=1)  # Ensure the canvas fills the heigh

    # Mini Mushroom
    icon = create_image_icon(content_frame, "assets/items/miniMushroom.png", 2, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=2, column=2)
    miniMushroomPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomPrice1.grid(row=2, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=2, column=4)
    miniMushroomPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomPrice2.grid(row=2, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=2, column=6)
    miniMushroomPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomPrice34.grid(row=2, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=2, column=8)
    miniMushroomShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomShopOdds12.grid(row=2, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=2, column=10)
    miniMushroomShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomShopOdds34.grid(row=2, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=2, column=12)
    miniMushroomSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomSpaceOdds1.grid(row=2, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=2, column=14)
    miniMushroomSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomSpaceOdds2.grid(row=2, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=2, column=16)
    miniMushroomSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomSpaceOdds34.grid(row=2, column=17)

    # Mega Mushroom
    icon = create_image_icon(content_frame, "assets/items/megaMushroom.png", 3, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=3, column=2)
    megaMushroomPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomPrice1.grid(row=3, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=3, column=4)
    megaMushroomPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomPrice2.grid(row=3, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=3, column=6)
    megaMushroomPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomPrice34.grid(row=3, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=3, column=8)
    megaMushroomShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomShopOdds12.grid(row=3, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=3, column=10)
    megaMushroomShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomShopOdds34.grid(row=3, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=3, column=12)
    megaMushroomSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomSpaceOdds1.grid(row=3, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=3, column=14)
    megaMushroomSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomSpaceOdds2.grid(row=3, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=3, column=16)
    megaMushroomSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    megaMushroomSpaceOdds34.grid(row=3, column=17)

    # Super Mini Mushroom
    icon = create_image_icon(content_frame, "assets/items/superMiniMushroom.png", 4, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=4, column=2)
    miniMushroomPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomPrice1.grid(row=4, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=4, column=4)
    miniMushroomPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomPrice2.grid(row=4, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=4, column=6)
    miniMushroomPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomPrice34.grid(row=4, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=4, column=8)
    miniMushroomShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomShopOdds12.grid(row=4, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=4, column=10)
    miniMushroomShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomShopOdds34.grid(row=4, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=4, column=12)
    miniMushroomSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomSpaceOdds1.grid(row=4, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=4, column=14)
    miniMushroomSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomSpaceOdds2.grid(row=4, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=4, column=16)
    miniMushroomSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMushroomSpaceOdds34.grid(row=4, column=17)

    # Super Mega Mushroom
    icon = create_image_icon(content_frame, "assets/items/superMegaMushroom.png", 5, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=5, column=2)
    superMegaMushroomPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomPrice1.grid(row=5, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=5, column=4)
    superMegaMushroomPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomPrice2.grid(row=5, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=5, column=6)
    superMegaMushroomPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomPrice34.grid(row=5, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=5, column=8)
    superMegaMushroomShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomShopOdds12.grid(row=5, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=5, column=10)
    superMegaMushroomShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomShopOdds34.grid(row=5, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=5, column=12)
    superMegaMushroomSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomSpaceOdds1.grid(row=5, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=5, column=14)
    superMegaMushroomSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomSpaceOdds2.grid(row=5, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=5, column=16)
    superMegaMushroomSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    superMegaMushroomSpaceOdds34.grid(row=5, column=17)

    # Mini-Mega Hammer
    icon = create_image_icon(content_frame, "assets/items/miniMegaHammer.png", 6, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=6, column=2)
    miniMegaHammerPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerPrice1.grid(row=6, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=6, column=4)
    miniMegaHammerPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerPrice2.grid(row=6, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=6, column=6)
    miniMegaHammerPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerPrice34.grid(row=6, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=6, column=8)
    miniMegaHammerShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerShopOdds12.grid(row=6, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=6, column=10)
    miniMegaHammerShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerShopOdds34.grid(row=6, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=6, column=12)
    miniMegaHammerSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerSpaceOdds1.grid(row=6, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=6, column=14)
    miniMegaHammerSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerSpaceOdds2.grid(row=6, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=6, column=16)
    miniMegaHammerSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    miniMegaHammerSpaceOdds34.grid(row=6, column=17)

    # Warp Pipe
    icon = create_image_icon(content_frame, "assets/items/warpPipe.png", 7, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=7, column=2)
    warpPipePrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipePrice1.grid(row=7, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=7, column=4)
    warpPipePrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipePrice2.grid(row=7, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=7, column=6)
    warpPipePrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipePrice34.grid(row=7, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=7, column=8)
    warpPipeShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipeShopOdds12.grid(row=7, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=7, column=10)
    warpPipeShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipeShopOdds34.grid(row=7, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=7, column=12)
    warpPipeSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipeSpaceOdds1.grid(row=7, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=7, column=14)
    warpPipeSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipeSpaceOdds2.grid(row=7, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=7, column=16)
    warpPipeSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    warpPipeSpaceOdds34.grid(row=7, column=17)

    # Swap Card
    icon = create_image_icon(content_frame, "assets/items/swapCard.png", 8, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=8, column=2)
    swapCardPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardPrice1.grid(row=8, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=8, column=4)
    swapCardPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardPrice2.grid(row=8, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=8, column=6)
    swapCardPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardPrice34.grid(row=8, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=8, column=8)
    swapCardShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardShopOdds12.grid(row=8, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=8, column=10)
    swapCardShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardShopOdds34.grid(row=8, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=8, column=12)
    swapCardSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardSpaceOdds1.grid(row=8, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=8, column=14)
    swapCardSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardSpaceOdds2.grid(row=8, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=8, column=16)
    swapCardSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    swapCardSpaceOdds34.grid(row=8, column=17)

    # Sparky Sticker
    icon = create_image_icon(content_frame, "assets/items/sparkySticker.png", 9, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=9, column=2)
    sparkyStickerPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerPrice1.grid(row=9, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=9, column=4)
    sparkyStickerPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerPrice2.grid(row=9, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=9, column=6)
    sparkyStickerPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerPrice34.grid(row=9, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=9, column=8)
    sparkyStickerShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerShopOdds12.grid(row=9, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=9, column=10)
    sparkyStickerShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerShopOdds34.grid(row=9, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=9, column=12)
    sparkyStickerSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerSpaceOdds1.grid(row=9, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=9, column=14)
    sparkyStickerSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerSpaceOdds2.grid(row=9, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=9, column=16)
    sparkyStickerSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    sparkyStickerSpaceOdds34.grid(row=9, column=17)

    # Gaddlight
    icon = create_image_icon(content_frame, "assets/items/gaddlight.png", 10, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=10, column=2)
    gaddlightPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightPrice1.grid(row=10, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=10, column=4)
    gaddlightPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightPrice2.grid(row=10, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=10, column=6)
    gaddlightPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightPrice34.grid(row=10, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=10, column=8)
    gaddlightShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightShopOdds12.grid(row=10, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=10, column=10)
    gaddlightShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightShopOdds34.grid(row=10, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=10, column=12)
    gaddlightSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightSpaceOdds1.grid(row=10, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=10, column=14)
    gaddlightSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightSpaceOdds2.grid(row=10, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=10, column=16)
    gaddlightSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    gaddlightSpaceOdds34.grid(row=10, column=17)

    # Chomp Call
    icon = create_image_icon(content_frame, "assets/items/chompCall.png", 11, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=11, column=2)
    chompCallPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallPrice1.grid(row=11, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=11, column=4)
    chompCallPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallPrice2.grid(row=11, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=11, column=6)
    chompCallPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallPrice34.grid(row=11, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=11, column=8)
    chompCallShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallShopOdds12.grid(row=11, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=11, column=10)
    chompCallShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallShopOdds34.grid(row=11, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=11, column=12)
    chompCallSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallSpaceOdds1.grid(row=11, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=11, column=14)
    chompCallSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallSpaceOdds2.grid(row=11, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=11, column=16)
    chompCallSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    chompCallSpaceOdds34.grid(row=11, column=17)

    # Bowser Suit
    icon = create_image_icon(content_frame, "assets/items/bowserSuit4.png", 12, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=12, column=2)
    bowserSuitPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitPrice1.grid(row=12, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=12, column=4)
    bowserSuitPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitPrice2.grid(row=12, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=12, column=6)
    bowserSuitPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitPrice34.grid(row=12, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=12, column=8)
    bowserSuitShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitShopOdds12.grid(row=12, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=12, column=10)
    bowserSuitShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitShopOdds34.grid(row=12, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=12, column=12)
    bowserSuitSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitSpaceOdds1.grid(row=12, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=12, column=14)
    bowserSuitSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitSpaceOdds2.grid(row=12, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=12, column=16)
    bowserSuitSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    bowserSuitSpaceOdds34.grid(row=12, column=17)

    # Boo's Crystal Ball
    icon = create_image_icon(content_frame, "assets/items/crystalBall.png", 13, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=13, column=2)
    crystalBallPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallPrice1.grid(row=13, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=13, column=4)
    crystalBallPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallPrice2.grid(row=13, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=13, column=6)
    crystalBallPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallPrice34.grid(row=13, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=13, column=8)
    crystalBallShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallShopOdds12.grid(row=13, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=13, column=10)
    crystalBallShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallShopOdds34.grid(row=13, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=13, column=12)
    crystalBallSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallSpaceOdds1.grid(row=13, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=13, column=14)
    crystalBallSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallSpaceOdds2.grid(row=13, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=13, column=16)
    crystalBallSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    crystalBallSpaceOdds34.grid(row=13, column=17)

    # Magic Lamp
    icon = create_image_icon(content_frame, "assets/items/magicLamp4.png", 14, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=14, column=2)
    magicLampPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampPrice1.grid(row=14, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=14, column=4)
    magicLampPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampPrice2.grid(row=14, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=14, column=6)
    magicLampPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampPrice34.grid(row=14, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=14, column=8)
    magicLampShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampShopOdds12.grid(row=14, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=14, column=10)
    magicLampShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampShopOdds34.grid(row=14, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=14, column=12)
    magicLampSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampSpaceOdds1.grid(row=14, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=14, column=14)
    magicLampSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampSpaceOdds2.grid(row=14, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=14, column=16)
    magicLampSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    magicLampSpaceOdds34.grid(row=14, column=17)

    # Item Bag
    icon = create_image_icon(content_frame, "assets/items/itemBag4.png", 15, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=15, column=2)
    itemBagPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagPrice1.grid(row=15, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=15, column=4)
    itemBagPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagPrice2.grid(row=15, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=15, column=6)
    itemBagPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagPrice34.grid(row=15, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=15, column=8)
    itemBagShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagShopOdds12.grid(row=15, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=15, column=10)
    itemBagShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagShopOdds34.grid(row=15, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=15, column=12)
    itemBagSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagSpaceOdds1.grid(row=15, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=15, column=14)
    itemBagSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagSpaceOdds2.grid(row=15, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=15, column=16)
    itemBagSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagSpaceOdds34.grid(row=15, column=17)

    # Bowser Phone
    icon = create_image_icon(content_frame, "assets/items/itemBag4.png", 15, 1)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n   1st  ", font=("Arial", 14))
    label.grid(row=15, column=2)
    itemBagPrice1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagPrice1.grid(row=15, column=3)
    label = ctk.CTkLabel(master=content_frame, text="  Cost\n    2nd  ", font=("Arial", 14))
    label.grid(row=15, column=4)
    itemBagPrice2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagPrice2.grid(row=15, column=5)
    label = ctk.CTkLabel(master=content_frame, text=" Cost\n  3rd / 4th ", font=("Arial", 14))
    label.grid(row=15, column=6)
    itemBagPrice34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagPrice34.grid(row=15, column=7)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n    Early   ", font=("Arial", 14))
    label.grid(row=15, column=8)
    itemBagShopOdds12 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagShopOdds12.grid(row=15, column=9)
    label = ctk.CTkLabel(master=content_frame, text=" Shop Odd\n     Late    ", font=("Arial", 14))
    label.grid(row=15, column=10)
    itemBagShopOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagShopOdds34.grid(row=15, column=11)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      1st ", font=("Arial", 14))
    label.grid(row=15, column=12)
    itemBagSpaceOdds1 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagSpaceOdds1.grid(row=15, column=13)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      2nd ", font=("Arial", 14))
    label.grid(row=15, column=14)
    itemBagSpaceOdds2 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagSpaceOdds2.grid(row=15, column=15)
    label = ctk.CTkLabel(master=content_frame, text="     Pickup Odd  \n      3rd / 4th ", font=("Arial", 14))
    label.grid(row=15, column=16)
    itemBagSpaceOdds34 = ctk.CTkEntry(master=content_frame, width=48, font=("Arial", 16, "bold"))
    itemBagSpaceOdds34.grid(row=15, column=17)
    items4 = ["None", "Mini Mushroom", "Mega Mushroom", "Super Mini Mushroom", "Super Mega Mushroom", "Mini-Mega Hammer", "Warp Pipe", "Swap Card", "Sparky Sticker", "Gaddlight", "Chomp Call", "Bowser Suit", "Boo's Crystal Ball", "Magic Lamp", "Item Bag"]

    label = ctk.CTkLabel(master=tabview.tab("Initial Items"), text=" Item 1:  ", font=("Arial", 16))
    label.grid(row=0, column=0)

    initalItem41 = ctk.CTkComboBox(master=tabview.tab("Initial Items"), values=items4)
    initalItem41.grid(row=0, column=1)

    label = ctk.CTkLabel(master=tabview.tab("Initial Items"), text=" Item 2:  ", font=("Arial", 16))
    label.grid(row=1, column=0)

    initalItem42 = ctk.CTkComboBox(master=tabview.tab("Initial Items"), values=items4)
    initalItem42.grid(row=1, column=1)

    label = ctk.CTkLabel(master=tabview.tab("Initial Items"), text=" Item 3:  ", font=("Arial", 16))
    label.grid(row=2, column=0)

    initalItem43 = ctk.CTkComboBox(master=tabview.tab("Initial Items"), values=items4)
    initalItem43.grid(row=2, column=1)

    parseButton = ctk.CTkButton(master=tabview.tab("Initial Items"), command=lambda: initialItemsEvent_mp4(initalItem41, initalItem42, initalItem43, items4), text="Generate Codes")
    parseButton.place(x=10, y=800)
    
    label = ctk.CTkLabel(master=tabview.tab("Lottery Rewards"), text=" 1st Place Prize (Coins):  ", font=("Arial", 16))
    label.grid(row=0, column=0, sticky="w")

    lotteryPrizeA =  ctk.CTkEntry(master=tabview.tab("Lottery Rewards"), width=48, font=("Arial", 16, "bold"), placeholder_text="100")
    lotteryPrizeA.grid(row=0, column=1, sticky="w")

    label = ctk.CTkLabel(master=tabview.tab("Lottery Rewards"), text=" 2nd Place Prize (Coins):  ", font=("Arial", 16))
    label.grid(row=1, column=0, sticky="w")

    lotteryPrizeB = ctk.CTkEntry(master=tabview.tab("Lottery Rewards"), width=48, font=("Arial", 16, "bold"), placeholder_text="30")
    lotteryPrizeB.grid(row=1, column=1, sticky="w")

    label = ctk.CTkLabel(master=tabview.tab("Lottery Rewards"), text=" 3rd Place Prize A (Item):  ", font=("Arial", 16))
    label.grid(row=2, column=0, sticky="w")

    lotteryPrizeC = ctk.CTkComboBox(master=tabview.tab("Lottery Rewards"), values=items4)
    lotteryPrizeC.grid(row=2, column=1, sticky="w")

    label = ctk.CTkLabel(master=tabview.tab("Lottery Rewards"), text=" 3rd Place Prize B (Item):  ", font=("Arial", 16))
    label.grid(row=3, column=0, sticky="w")

    lotteryPrizeD = ctk.CTkComboBox(master=tabview.tab("Lottery Rewards"), values=items4)
    lotteryPrizeD.grid(row=3, column=1, sticky="w")

    parseButton = ctk.CTkButton(master=tabview.tab("Lottery Rewards"), command=lambda: itemsLotteryEvent_mp4(lotteryPrizeA, lotteryPrizeB, lotteryPrizeC, lotteryPrizeD, items4), text="Generate Codes")
    parseButton.place(x=10, y=800)

    spaces4 = ["None", "Invisible Space", "Blue Space", "Red Space", "Bowser Space", "Mushroom Space", "Battle Space", "Happening Space", "Chance Time Space", "Spring Space"]

    label = ctk.CTkLabel(master=tabview.tab("Space Replacement"), text=" Replace  ", font=("Arial", 16))
    label.grid(row=0, column=0)

    spaceRep411 = ctk.CTkComboBox(master=tabview.tab("Space Replacement"), values=spaces4)
    spaceRep411.grid(row=0, column=1)

    label = ctk.CTkLabel(master=tabview.tab("Space Replacement"), text=" with ", font=("Arial", 16))
    label.grid(row=0, column=2)

    spaceRep421 = ctk.CTkComboBox(master=tabview.tab("Space Replacement"), values=spaces4)
    spaceRep421.grid(row=0, column=3)

    label = ctk.CTkLabel(master=tabview.tab("Space Replacement"), text=" (Slot A) ", font=("Arial", 16))
    label.grid(row=0, column=4)

    label = ctk.CTkLabel(master=tabview.tab("Space Replacement"), text=" Replace  ", font=("Arial", 16))
    label.grid(row=1, column=0)

    spaceRep412 = ctk.CTkComboBox(master=tabview.tab("Space Replacement"), values=spaces4)
    spaceRep412.grid(row=1, column=1)

    label = ctk.CTkLabel(master=tabview.tab("Space Replacement"), text=" with ", font=("Arial", 16))
    label.grid(row=1, column=2)

    spaceRep422 = ctk.CTkComboBox(master=tabview.tab("Space Replacement"), values=spaces4)
    spaceRep422.grid(row=1, column=3)

    label = ctk.CTkLabel(master=tabview.tab("Space Replacement"), text=" (Slot B) ", font=("Arial", 16))
    label.grid(row=1, column=4)

    parseButton = ctk.CTkButton(master=tabview.tab("Space Replacement"), command=lambda: spaceReplaceEvent_mp4(spaceRep411, spaceRep421, spaceRep412, spaceRep422, spaces4), text="Generate Codes")
    parseButton.place(x=10, y=800)

    icon = create_image_icon(tabview.tab("Star Handicaps"), "assets/eventTags/starSpace.png", 0, 0)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" P1 Starts with  ", font=("Arial", 16))
    label.grid(row=0, column=1)
    p1Stars = ctk.CTkEntry(master=tabview.tab("Star Handicaps"), width=48, font=("Arial", 16, "bold"))
    p1Stars.grid(row=0, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" Stars ", font=("Arial", 16))
    label.grid(row=0, column=3)
    
    icon = create_image_icon(tabview.tab("Star Handicaps"), "assets/eventTags/starSpace.png", 1, 0)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" P2 Starts with  ", font=("Arial", 16))
    label.grid(row=1, column=1)
    p2Stars = ctk.CTkEntry(master=tabview.tab("Star Handicaps"), width=48, font=("Arial", 16, "bold"))
    p2Stars.grid(row=1, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" Stars ", font=("Arial", 16))
    label.grid(row=1, column=3)

    icon = create_image_icon(tabview.tab("Star Handicaps"), "assets/eventTags/starSpace.png", 2, 0)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" P3 Starts with  ", font=("Arial", 16))
    label.grid(row=2, column=1)
    p3Stars = ctk.CTkEntry(master=tabview.tab("Star Handicaps"), width=48, font=("Arial", 16, "bold"))
    p3Stars.grid(row=2, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" Stars ", font=("Arial", 16))
    label.grid(row=2, column=3)

    icon = create_image_icon(tabview.tab("Star Handicaps"), "assets/eventTags/starSpace.png", 3, 0)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" P4 Starts with  ", font=("Arial", 16))
    label.grid(row=3, column=1)
    p4Stars = ctk.CTkEntry(master=tabview.tab("Star Handicaps"), width=48, font=("Arial", 16, "bold"))
    p4Stars.grid(row=3, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Star Handicaps"), text=" Stars ", font=("Arial", 16))
    label.grid(row=3, column=3)

    parse_stars_button = ctk.CTkButton(master=tabview.tab("Star Handicaps"), command=lambda: handicapEvent_mp4(p1Stars, p2Stars, p3Stars, p4Stars), text="Generate Codes")
    parse_stars_button.place(x=10, y=800)

    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Replace 5 Coins with  ", font=("Arial", 16))
    label.grid(row=0, column=1, pady=10)
    fiveCoins = ctk.CTkEntry(master=tabview.tab("Battle Minigame"), width=48, font=("Arial", 16, "bold"))
    fiveCoins.grid(row=0, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Coins ", font=("Arial", 16))
    label.grid(row=0, column=3)
    
    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Replace 10 Coins with  ", font=("Arial", 16))
    label.grid(row=1, column=1, pady=10)
    tenCoins = ctk.CTkEntry(master=tabview.tab("Battle Minigame"), width=48, font=("Arial", 16, "bold"))
    tenCoins.grid(row=1, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Coins ", font=("Arial", 16))
    label.grid(row=1, column=3)

    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Replace 20 Coins with  ", font=("Arial", 16))
    label.grid(row=2, column=1, pady=10)
    twentyCoins = ctk.CTkEntry(master=tabview.tab("Battle Minigame"), width=48, font=("Arial", 16, "bold"))
    twentyCoins.grid(row=2, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Coins ", font=("Arial", 16))
    label.grid(row=2, column=3)

    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Replace 30 Coins with  ", font=("Arial", 16))
    label.grid(row=3, column=1, pady=10)
    thirtyCoins = ctk.CTkEntry(master=tabview.tab("Battle Minigame"), width=48, font=("Arial", 16, "bold"))
    thirtyCoins.grid(row=3, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Coins ", font=("Arial", 16))
    label.grid(row=3, column=3)

    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Replace 50 Coins with  ", font=("Arial", 16))
    label.grid(row=4, column=1, pady=10)
    fiftyCoins = ctk.CTkEntry(master=tabview.tab("Battle Minigame"), width=48, font=("Arial", 16, "bold"))
    fiftyCoins.grid(row=4, column=2)
    label = ctk.CTkLabel(master=tabview.tab("Battle Minigame"), text=" Coins ", font=("Arial", 16))
    label.grid(row=4, column=3)

    parse_stars_button = ctk.CTkButton(master=tabview.tab("Battle Minigame"), command=lambda: battleCoins_mp4(fiveCoins, tenCoins, twentyCoins, thirtyCoins, fiftyCoins), text="Generate Codes")
    parse_stars_button.place(x=10, y=800)

    return frame