def itemsEvent_mp8(twicePrice4, twiceWeight4, thricePrice4, thriceWeight4, slowgoPrice4, slowgoWeight4, springoPrice4, springoWeight4, cashzapPrice4, cashzapWeight4, vampirePrice4, vampireWeight4, bitsizePrice4, bitsizeWeight4, blowayPrice4, blowayWeight4, bowloPrice4, bowloWeight4, weegleePrice4, weegleeWeight4, thwompPrice4, thwompWeight4, bulletPrice4, bulletWeight4, bowserPrice4, bowserWeight4, dueloPrice4, dueloWeight4):
    if not twicePrice4.get() or not twiceWeight4.get() or not thricePrice4.get() or not thriceWeight4.get() or not springoPrice4.get() or not springoWeight4.get() or not slowgoPrice4.get() or not slowgoWeight4.get() or not cashzapPrice4.get() or not cashzapWeight4.get() or not bitsizePrice4.get() or not bitsizeWeight4.get() or not blowayPrice4.get() or not blowayWeight4.get() or not vampirePrice4.get() or not vampireWeight4.get() or not bowloPrice4.get() or not bowloWeight4.get() or not weegleePrice4.get() or not weegleeWeight4.get() or not bowserPrice4.get() or not bowserWeight4.get() or not bulletPrice4.get() or not bulletWeight4.get() or not thwompPrice4.get() or not thwompWeight4.get() or not dueloPrice4.get()  or not dueloWeight4.get():
        createDialog("Error", "error", "Please fill out all the boxes.", None)
        return
    twicePrice4 = twicePrice4.get()
    twiceWeight4 = twiceWeight4.get()
    thricePrice4 = thricePrice4.get()
    thriceWeight4 = thriceWeight4.get()
    slowgoPrice4 = slowgoPrice4.get()
    slowgoWeight4 = slowgoWeight4.get()
    springoPrice4 = springoPrice4.get()
    springoWeight4 = springoWeight4.get()
    cashzapPrice4 = cashzapPrice4.get()
    cashzapWeight4 = cashzapWeight4.get()
    bitsizePrice4 = bitsizePrice4.get()
    bitsizeWeight4 = bitsizeWeight4.get()
    blowayPrice4 = blowayPrice4.get()
    blowayWeight4 = blowayWeight4.get()
    vampirePrice4 = vampirePrice4.get()
    vampireWeight4 = vampireWeight4.get()
    weegleePrice4 = weegleePrice4.get()
    weegleeWeight4 = weegleeWeight4.get()
    bowserPrice4 = bowserPrice4.get()
    bowserWeight4 = bowserWeight4.get()
    bowloPrice4 = bowloPrice4.get()
    bowloWeight4 = bowloWeight4.get()
    bulletPrice4 = bulletPrice4.get()
    bulletWeight4 = bulletWeight4.get()
    thwompPrice4 = thwompPrice4.get()
    thwompWeight4 = thwompWeight4.get()
    dueloPrice4 = dueloPrice4.get()
    dueloWeight4 = dueloWeight4.get()
    orbWeightTotal = int(twiceWeight4) + int(thriceWeight4) + int(slowgoWeight4) + int(springoWeight4) + int(cashzapWeight4) + int(bitsizeWeight4) + int(blowayWeight4) + int(vampireWeight4) + int(weegleeWeight4) + int(bowserWeight4) + int(bowloWeight4) + int(bulletWeight4) + int(thwompWeight4) + int(dueloWeight4)
    orbPriceMin = find_lowest_integer(*[int(twicePrice4), int(thricePrice4), int(slowgoPrice4), int(springoPrice4), int(cashzapPrice4), int(bitsizePrice4), int(blowayPrice4), int(vampirePrice4), int(weegleePrice4), int(bowserPrice4), int(bowloPrice4), int(bulletPrice4), int(thwompPrice4), int(dueloPrice4)])
    
    def calculateWeight(weight):
        percentage = (int(weight) / orbWeightTotal) * 100
        if 0< percentage < 1:
            return str(math.ceil(percentage))
        return str(round(percentage))

    twiceWeight4 = calculateWeight(twiceWeight4)
    thriceWeight4 = calculateWeight(thriceWeight4)
    springoWeight4 = calculateWeight(springoWeight4)
    slowgoWeight4 = calculateWeight(slowgoWeight4)
    cashzapWeight4 = calculateWeight(cashzapWeight4)
    bitsizeWeight4 = calculateWeight(bitsizeWeight4)
    blowayWeight4 = calculateWeight(blowayWeight4)
    vampireWeight4 = calculateWeight(vampireWeight4)
    weegleeWeight4 = calculateWeight(weegleeWeight4)
    bowserWeight4 = calculateWeight(bowserWeight4)
    bowloWeight4 = calculateWeight(bowloWeight4)
    bulletWeight4 = calculateWeight(bulletWeight4)
    thwompWeight4 = calculateWeight(thwompWeight4)
    dueloWeight4 = calculateWeight(dueloWeight4)
    
    
    generatedCode = getCandyModsEight(twicePrice4, twiceWeight4, thricePrice4, thriceWeight4, slowgoPrice4, slowgoWeight4, springoPrice4, springoWeight4, cashzapPrice4, cashzapWeight4, bitsizePrice4, bitsizeWeight4, blowayPrice4, blowayWeight4, vampirePrice4, vampireWeight4, weegleePrice4, weegleeWeight4, bowserPrice4, bowserWeight4, bowloPrice4, bowloWeight4, bulletPrice4, bulletWeight4, thwompPrice4, thwompWeight4, dueloPrice4, dueloWeight4, orbPriceMin)
    generatedCode = generatedCode.strip()
    pyperclip.copy(generatedCode)
    print("Generated code copied to the clipboard.")
    createDialog("Operation Sucessful", "success", "Generated codes copied to clipboard!.", None)